import {baseUrl} from './globalConfig.js'
export const WS_URL = baseUrl + '/stomp'
export const WS_DEST_TOPIC = '/topic'
export const WS_DEST_USER = '/toUser'
export const WS_SEND_WEB = '/weby'
export const WS_STOMP = '/stomp'
